sudo: required
language: python
python:
    - "3.6"

script:
    - export PYTHONPATH="$(pwd)"
    - pip install codecov
    - cd test
    - coverage run -m unittest discover -v --pattern=test_*.py

after_success:
    - codecov

notifications:
    email: false